name: Java CI

on:
  push:
  pull_request:
  schedule: [ cron: '19 1 * * 5' ] # weekly: At 01:19 on Friday

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 17 ]
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'

      - name: Build (skipITs)
        run: mvn --batch-mode --show-version --no-transfer-progress -D CI=GitHub install
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install -PIT --with-deps"
      - name: Run ITs
        run: mvn -PIT -D CI=GitHub verify
